name: 'macOS '

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dynare_6_0_matlab_r2024a_macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2024a
          products: Symbolic_Math_Toolbox Statistics_and_Machine_Learning_Toolbox Optimization_Toolbox Econometrics_Toolbox Parallel_Computing_Toolbox Control_System_Toolbox Global_Optimization_Toolbox
          cache: true

      - name: Download Dynare .pkg for macOS ARM64
        run: |          
          curl -L "https://www.dynare.org/release/macos-arm64/dynare-6.0-arm64.pkg" -o "dynare-6.0-arm64.pkg"
        shell: bash

      - name: Install Dynare from the .pkg file (without sudo)
        run: |
          pkgutil --expand dynare-6.0-arm64.pkg Dynare-6.0-arm64
          cd Dynare-6.0-arm64/dynare-6.0-arm64.pkg/
          tar -zxvf Payload -C ../
          ls
          cd ..
          cd ..
        shell: bash

      - name: Run exercises 1 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/matlab");
            quickTourMatlab;
            cd("../dynare");
            dynare arma11 console
            cd("../matlab");
            arma11CompareMATLABWithDynare;

      - name: Run exercises 2 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/matlab");
            rbcLogutilSteadyStateTest;
            cd("../dynare");
            dynare rbcLogutil console
            cd("../matlab");
            rbcCRRASteadyStateTest;
            cd("../dynare");
            dynare rbcCRRA console
            dynare BaxterKingSteadyState console
            dynare BaxterKingGrowthSteadyState console
            cd("../replications/Baxter_King_1993");
            dynare Baxter_King_1993_figure_2 console

      - name: Run exercises 3 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/replications/Baxter_King_1993");
            dynare Baxter_King_1993_figure_3 console
            cd("../../matlab")
            symbolicToolboxIllustation;
            matrixAlgebraEigenvalues;
            matrixAlgebraKroneckerFormula;
            matrixAlgebraCholesky;
            matrixAlgebraCompareLyapunovSolvers;
            preprocessingComparisonRBC;

      - name: Run exercises 4 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/dynare");
            dynare nk console

      - name: Run exercises 5 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/matlab");
            numericalOptimizationExamples;
            steadystateRBC;

      - name: Run exercises 6 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/dynare");
            dynare nk2co_common console
            dynare nk2co_temp_monpol_surprise console
            dynare nk2co_temp_monpol_announced console
            dynare nk2co_perm_infltarget_surprise console
            dynare nk2co_perm_tax_announced console
            nk2co_understand_perfect_foresight;

      - name: Run exercises 7 codes
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath("Dynare-6.0-arm64/matlab");
            cd("progs/replications/Eichenbaum_Rebelo_Trabandt_2022");
            dynare ert_model_sticky_steady console
            dynare ert_model_initval console
            dynare ert_model_histval console
            dynare ert_model_no_homotopy console
            dynare ert_model_homotopy console
            dynare ert_model_figures_demand console
            dynare ert_model_figures_supply console
            dynare ert_model_figures_both console
