name: LaTeX

on:
  push:
    branches:
      - main
    tags:
      - '2024-week-*'
      - '2025-week-*'
  workflow_dispatch:

jobs:
  build_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX exercises
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "exercises*.tex"
          work_in_root_file_dir: true

      - name: Compile LaTeX exams
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "exam/*_exam_*.tex"
          work_in_root_file_dir: true

      - name: Compile LaTeX slides
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "slides/*.tex"
          work_in_root_file_dir: true

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/2025-week-')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "exercises*.pdf, exam/*_exam_*.pdf, slides/slides_*.pdf"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}